"""empty message

Revision ID: 91514b3b1359
Revises: 3fb8083c9046
Create Date: 2025-10-03 10:43:55.979737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91514b3b1359'
down_revision: Union[str, Sequence[str], None] = '3fb8083c9046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'change_users_accounts_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('change_users_accounts_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
